angular.module('controller').
controller('loginController',['$scope','$state','localStorageService','$http',function(s,$state,storage,$http){
   s.login=function(){
        $http.post('/FrontLogin/Login',{
            Num:s.Num,
            Passwd:s.Password
        }).success(function(data){
            alert(data)
            storage.set('Num',s.Num);
            storage.set('Passwd',s.Password);
            $state.go('index.firstPage.fp') 
        }).error(function(error){
            alert(error)     
        })
   }
}]);